name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    name: Validate Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Validate Maven project
        run: mvn validate

      - name: Compile code
        run: mvn clean compile

      - name: Run unit tests
        run: mvn test

      - name: Verify package
        run: mvn verify

      - name: Check code style (optional)
        continue-on-error: true
        run: mvn checkstyle:check || true

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: All checks passed
        run: echo "✅ All quality checks passed successfully!"
