name: Continuous Integration

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Validate Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Validate Maven project
        run: mvn validate

      - name: Compile code
        run: mvn clean compile

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'master'
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run unit tests
        run: mvn test

      - name: Verify package
        run: mvn verify

      - name: Check code style (optional)
        continue-on-error: true
        run: mvn checkstyle:check || true
